# our base image
FROM python:3-onbuild

#RUN pip install imageio
#RUN pip install matplotlib

# specify the port number the container should expose
EXPOSE 5000

# run the application
CMD ["python", "./appimclass.py"]
